{% set name = "EvoScope" %}
{% set version = "1.0.0" %}

package:
  name: "{{ name }}"
  version: "{{ version }}"

source:
  url: "https://github.com/Maxime5G/{{ name }}/archive/refs/tags/v{{ version }}.tar.gz"
  sha256: 00d05eb8e1482028f2abd7d83572591e18333d4e13fbac0ddf19f4bf75242b2d

build:
  number: 0

requirements:
  build: 
    - make
    - {{ compiler('c') }}
  host:
  run:
    - r-base >= 4.0.0
    - pastml >= 1.9.3
    - r-tidyverse
    - r-ape
    - r-gplots

test:
  commands:
    - evoscope -h

about:
  home: "https://github.com/Maxime5G/EvoScope"
  license: GPL-3.0
  license_file: "EvoScope/LICENSE"
  summary: "EvoScope: EVOlutionary Study of Correlations of Occurrences on a Phylogeny."
  description: |
    EvoScope is a wrapper combining two phylogenetic tools to assess correlated evolution between a pair of traits reconstructed on a phylogenetic tree.

extra:
  recipe-maintainers:
    - Maxime5G
